### ISSUE TITLE
Issues with heroku?

### ISSUE THREAD

**Issue by ghost** [cllns/material_design_lite-rails#6]
Hey!

Has anyone tried deploying to heroku?

Its not working for me for some reason.

URL: https://staging.counterstrike.io/
Screenshot: http://i.imgur.com/6rtvaSw.png
What it looks like in development (what its supposed to look like): http://i.imgur.com/aCHRvKY.png

Thanks.

**Comment by cllns** [comment]
Ooh, thanks so much for reporting this. I haven't had the chance to deploy this anywhere, so it's super valuable. 

I'll try it out now and keep you updated.

**Comment by ghost** [comment]
Awesome, thanks.

**Comment by cllns** [comment]
Hm, I just deployed a completely vanilla Rails 4.2.0, with Ruby 2.2 app fine here: http://test-mdl.herokuapp.com/

**Comment by nahtnam** [comment]
Can you add a header or something to it? As you can see, the footer works
fine but the header does not...

**Comment by cllns** [comment]
Yea, I realized I need to do that, so I deleted my comment :P 

Making this comment so you can see the response, but I'm going delete to your comment and mine, to avoid confusion :)

**Comment by cllns** [comment]
Just deployed a site here, with a header that uses CSS and JS (click the hamburger or search bar): http://test-mdl.herokuapp.com/ and it seems to work fine. When I click a link, the JS stop working, but no errors are triggered. I think that might be an effect of turbolinks  :sweat_smile: 

Rails 4.2.0
And Ruby 2.0 (on heroku) / Ruby 2.2 (on dev)

Are you using the [`rails_12factor`](https://github.com/heroku/rails_12factor) gem? I know that does stuff with assets.

**Comment by ghost** [comment]
It didnt work with rails12factor so i added it and it still doesnt work.

Can you push it to github so I can compare it with my site?

**Comment by cllns** [comment]
Here you go! https://github.com/cllns/test-mdl

**Comment by ghost** [comment]
Thats really weird. here are my application files: https://gist.github.com/nahtnam/1b5cdc96f7c2dd8d2e05

Do you see anything weird?

**Comment by cllns** [comment]
Yours looks like a JS error to me. There's no errors in the console, but the styles (fonts, footer color) seems OK.

Try commenting out Ember and see if that works.
Also maybe try moving the order of the JS files?

I don't think it matters, but I prefer the Sass import syntax to the CSS manifest file syntax.
Even more than that, I think you should pick a single one and stick to it.

**Comment by ghost** [comment]
What do you mean? I am using the Sass import syntax right?

Everything is working fine in development, but not in production. It probably does have something to do with javascript. Ill try messing around with the order and stuff. Let me know if you come up with a better idea though.

**Comment by nahtnam** [comment]
@cllns Hey!

I still cant figure it out. I tried changing the order and its not working. Would you be able to take a look at my code? https://goo.gl/2g6tPf

Thanks.

**Comment by ghost** [comment]
Fixed.

It had to do with the css caching of cloudflare.
